# Generated by Django 3.1.7 on 2021-04-04 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210331_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='page_in_vkontakte',
            field=models.CharField(blank=True, max_length=128, verbose_name='Страница во ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 15, 0, 39, 813228, tzinfo=utc)),
        ),
    ]
